# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://ncoop57.github.io/cute_ranking/"

git_url = "https://github.com/ncoop57/cute_ranking/tree/main/"

def custom_doc_links(name): return None
